# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# WEBSITE
title: Khoa Nguyen
name: Khoa Nguyen
description: "My personal website for everything tech-related."
# (>) means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
keywords: "Khoa LT Nguyen, Khoa Nguyen, Khoa, knguyen18, gh-pages, personal website"
width: large

# AUTHOR
author: Khoa Nguyen
  #name: Khoa Nguyen
  #bio: "I'm a tech nerd, and I'm proud of it."

# SOCIAL
quora: Khoa-Nguyen-302
twitter: khoaltn
github:  khoaltn
linkedin: khoaltn
email: knguyen18@wooster.edu
external-image: false
picture: assets/images/profile.png
  
# MISC
projects: false
about: true
blog: true
resume: true
read-time: true
show-tags: true
related: true
show-author: true
animation: true
analytics-google: UA-90057261-1

sass:
  sass_dir: _sass
  style: :compressed
  
# Build settings
highlighter: rouge
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
